roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "true"
  extraEnvs:
    - name: xpack.security.enabled
      value: "false"
    - name: xpack.monitoring.enabled
      value: "false"
    - name: xpack.ml.enabled
      value: "false"
    - name: xpack.graph.enabled
      value: "false"
    - name: xpack.watcher.enabled
      value: "false"
    - name: ES_JAVA_OPTS
      value: "-Xmx1g -Xms1g"

replicas: 1
minimumMasterNodes: 1
imageTag: "8.1.0"

esJavaOpts: "-Xmx1g -Xms1g"

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi

persistence:
  enabled: true
  labels:
    enabled: false
  annotations: {}

ingress:
  enabled: true
#  ingressClassName: "nginx"
  labels: {}
  annotations:
    ingressClassName: nginx
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-nginx
  pathtype: ImplementationSpecific
  hosts:
    - host: es.elasticdata.io
      paths:
        - path: /
#  tls:
#    - secretName: es-letsencrypt-tls
#      hosts:
#        - es.elasticdata.io

nameOverride: ""