{{- if .Values.pv.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.mongo.path }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}