agent:
  envVars:
    - name: DOCKER_CONTAINER_PREFIX
      value: bombascter
    - name: DOCKER_CONTAINER_LOGIN
      value: bombascter
    - name: DOCKER_CONTAINER_PASSWORD
      value: Prisoner31

controller:
  tag: 2.332.3-lts-jdk11
  adminPassword: "!Prisoner31!"
  ingress:
    enabled: true
    annotations:
      ingressClassName: nginx
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.elasticdata.io
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  installPlugins:
    - kubernetes:1.31.3
    - workflow-aggregator:2.6
    - configuration-as-code:1414.v878271fc496f
    - credentials-binding:523.vd859a_4b_122e6
    - git:4.11.1
    - pipeline-github-lib:36.v4c01db_ca_ed16
    - ghprb:1.42.2
    - blueocean:1.25.3