agent:
  envVars:
    - name: DOCKER_CONTAINER_PREFIX
      value: bombascter
    - name: DOCKER_CONTAINER_LOGIN
      value: bombascter
    - name: DOCKER_CONTAINER_PASSWORD
      value: Prisoner31

controller:
  tag: 2.332.3-lts-jdk11
  adminPassword: "!Prisoner31!"
  ingress:
    enabled: true
    annotations:
      ingressClassName: nginx
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.elasticdata.io
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 1500m
      memory: 1024Mi
  installPlugins:
    - kubernetes:3845.va_9823979a_744
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - configuration-as-code:1569.vb_72405b_80249
    - credentials-binding:523.vd859a_4b_122e6
    - git:5.0.0
    - pipeline-github-lib:38.v445716ea_edda_
    - ghprb:1.42.2
    - blueocean:1.27.1
