apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    helm.sh/chart: {{ include "rabbitmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: http
      port: 15672
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
