persistence:
  enabled: true
  size: 20Gi

resources:
  requests:
    memory: 512Mi

replicas: 1
mode: standalone

rootUser: "elasticdataio"
rootPassword: "elasticdataio"

users:
  - accessKey: elasticdataio
    secretKey: wJalrXUtnFEMI/9874c97c907209cpuvpw97bpb/asdasdasdasdasd
    policy: consoleAdmin

consoleIngress:
  enabled: true
  labels: {}
  annotations:
    ingressClassName: nginx
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-nginx
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.allow-http: "false"
    # kubernetes.io/ingress.global-static-ip-name: ""
    # nginx.ingress.kubernetes.io/secure-backends: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  path: /
  hosts:
    - storage.elasticdata.io
  tls:
    - secretName: minio-letsencrypt-tls
      hosts:
        - storage.elasticdata.io